# Generated by Django 4.0.3 on 2022-03-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthomniaapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artistId',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='moodId',
            new_name='mood',
        ),
    ]
