# Generated by Django 4.0.3 on 2022-03-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthomniaapi', '0002_rename_userid_artist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='mood',
            field=models.ManyToManyField(related_name='mood', to='synthomniaapi.mood'),
        ),
    ]
