# Generated by Django 4.0.3 on 2022-04-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synthomniaapi', '0003_artist_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synthomniaapi.artist'),
        ),
    ]
