# Generated by Django 4.0.3 on 2022-04-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthomniaapi', '0004_alter_track_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
    ]
